import { FC } from 'react';
import CompanyCard from './CompanyCard'; // Import the CompanyCard component

const gridStyle: React.CSSProperties = {
  display: 'flex',
  flexWrap: 'wrap',
  flexBasis: 'calc(20% - 50px)',
  justifyContent: 'space-around',
  alignItems: 'flex-start',
  gap: 'clamp(2px, 5vw, 40px)',
  margin: '0 clamp(5vw, 18vw, 25vw)',
  maxWidth: '1500px'
};

// This array should eventually come from a database or API call
const companyData = [
    {
        logoSrc: './companyLogos/Abode.svg',
        about: 'Company1 is a leading innovator in the tech industry, known for its cutting-edge solutions.',
        websiteUrl: 'http://www.company1.com',
        foundedDate: 'January 1, 2010',
        founders: ['Founder One', 'Founder Two'],
        stageInvested: 'Series A',
        sector: 'Technology',
        coInvestors: ['Investor A', 'Investor B'],
      },
      {
        logoSrc: './companyLogos/Acctual.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Archer.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/BananaDev.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Bowtie.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Bump.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Carmatic.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/CastAI.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/ClarityValue.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Deasie.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Eqtble.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Furo.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Homeflow.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Hona.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Leaseup.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Mortar.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Olive.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/OneImaging.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/OttoAI.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Packsmith.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Palm.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Pave.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Pier.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Rebuy.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Reset.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Sante.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Scanbase.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/SnapRefund.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Transcrypts.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Transend.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Trestle.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Trigo.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Vigil.png',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
      {
        logoSrc: './companyLogos/Parallel.svg',
        about: 'about',
        websiteUrl: 'website',
        foundedDate: 'founded date',
        founders: ['founder one', 'founder two'],
        stageInvested: 'seed',
        sector: 'sector',
        coInvestors: ['Investor C', 'Investor D'],
      },
];

const CompanyGrid: FC = () => {
  return (
    <div style={gridStyle} className="company-grid-margin">
      {companyData.map((company, index) => (
        <CompanyCard
          key={index}
          logoSrc={company.logoSrc}
          about={company.about}
          websiteUrl={company.websiteUrl}
          foundedDate={company.foundedDate}
          founders={company.founders}
          stageInvested={company.stageInvested}
          sector={company.sector}
          coInvestors={company.coInvestors}
        />
      ))}
    </div>
  );
};

export default CompanyGrid;
